# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '옵션설정.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json
import sys

class Option_Form(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.initUI()
    def initUI(self):
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(10, 80, 411, 481))
        self.frame.setFixedSize(411, 481)
        self.frame.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setStyleSheet("color: black;"
                       "background-color: #FFFFFF;"
                       "border-style: solid;"
                       "border-color: #ff901E;"
                       "border-radius: 5px")

        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(60, 10, 31, 31))
        combolist = ["key : spacebar","key : →","key : ←","key : ↑","key : ↓","Key : f","Key : c","Key : k","Key : esc"]
        #첫번째줄
        self.lbl = QtWidgets.QLabel(self.frame)
        self.lbl.setGeometry(QtCore.QRect(50, 50, 80, 80))
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(200, 70, 111, 41))
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(340, 65, 50, 50))
        self.comboBox.addItems(combolist)

        #두번째줄
        self.lbl2 = QtWidgets.QLabel(self.frame)
        self.lbl2.setGeometry(QtCore.QRect(50, 160, 80, 80))
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(200, 180, 111, 41))
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setGeometry(QtCore.QRect(340, 175, 50, 50))
        self.comboBox_2.addItems(combolist)

        #세번째줄
        self.lbl3 = QtWidgets.QLabel(self.frame)
        self.lbl3.setGeometry(QtCore.QRect(50, 270, 80, 80))
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setGeometry(QtCore.QRect(200, 290, 111, 41))
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_3.setGeometry(QtCore.QRect(340, 285, 50, 50))
        self.comboBox_3.addItems(combolist)

        #네번째줄
        self.lbl4 = QtWidgets.QLabel(self.frame)
        self.lbl4.setGeometry(QtCore.QRect(50, 380, 80, 80))
        self.comboBox_4 = QtWidgets.QComboBox(self.frame)
        self.comboBox_4.setGeometry(QtCore.QRect(200, 400, 111, 41))
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_4.setGeometry(QtCore.QRect(340, 395, 50, 50))
        self.comboBox_4.addItems(combolist)
        font = QtGui.QFont()
        font.setFamily("야놀자 야체 R")
        font.setPointSize(18)
        #버튼
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(320, 20, 101, 41))
        
        self.pushButton.setFont(font)
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 20, 101, 41))
        self.pushButton_2.setFont(font)

        #JSON에서 읽어온 설정값 세팅
        self.setOption()
        #UI 셋팅
        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "동작 설정"))
        Form.setWindowIcon(QtGui.QIcon("view/swipe.png"))
        Form.setStyleSheet("color: black;"
                       "background-color: #fdd8a2;"
                       "border-style: solid;"
                       "border-color: #fdd8a2;"
                       "border-radius: 5px;")
        font = QtGui.QFont()
        font.setFamily("야놀자 야체 R")
        font.setPointSize(18)
        
        self.label_3.setText(_translate("Form", "동작"))
        self.label_3.setFont(font)

        font.setPointSize(15)
        self.checkBox.setText(_translate("Form", "사용"))
        self.checkBox.setFont(font)
        self.checkBox_2.setText(_translate("Form", "사용 "))
        self.checkBox_2.setFont(font)
        self.checkBox_3.setText(_translate("Form", "사용 "))
        self.checkBox_3.setFont(font)
        self.checkBox_4.setText(_translate("Form", "사용 "))
        self.checkBox_4.setFont(font)
        
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox_2.setFont(font)
        self.comboBox_3.setFont(font)
        self.comboBox_4.setFont(font)
        self.pushButton.setText(_translate("Form", "저장"))
        self.pushButton.setStyleSheet("color: white;"
	"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 190, 11, 255), stop:1 rgba(251, 86, 7, 255));"
	"border-radius: 20px;")
        self.pushButton_2.setText(_translate("Form", "취소"))
        self.pushButton_2.setStyleSheet(
            "background-color: #FFFFFF;"
            "border-style: solid;"
            "border-color: #ff901E;"
            "border-radius: 20px;"
            "border-width: 3px;")
        self.pushButton.clicked.connect(self.onOKButtonClicked)
        self.pushButton_2.clicked.connect(self.onCancelButtonClicked)
    def setOption(self):
        _translate = QtCore.QCoreApplication.translate
        self.lbl.setPixmap(QtGui.QPixmap("view/finger/rnr_up.png").scaledToWidth(80))
        self.lbl2.setPixmap(QtGui.QPixmap("view/finger/right_move.png").scaledToWidth(80))
        self.lbl3.setPixmap(QtGui.QPixmap("view/finger/left_move.png").scaledToWidth(80))
        self.lbl4.setPixmap(QtGui.QPixmap("view/finger/5_3.png").scaledToWidth(80))
        #json읽어오기
        data_json = self.jsonRead()
        #첫번째라인셋팅
        self.comboBox.setCurrentIndex(int(data_json["1"]["action"]))
        self.checkBox.setChecked(bool(data_json["1"]["bool"]))
        self.comboBox.setStyleSheet("border-width: 3px;")
        #두번째라인셋팅
        self.comboBox_2.setCurrentIndex(int(data_json["2"]["action"]))
        self.checkBox_2.setChecked(bool(data_json["2"]["bool"]))
        self.comboBox_2.setStyleSheet("border-width: 3px;")
        #세번째라인셋팅
        self.comboBox_3.setCurrentIndex(int(data_json["3"]["action"]))
        self.checkBox_3.setChecked(bool(data_json["3"]["bool"]))
        self.comboBox_3.setStyleSheet("border-width: 3px;")
        #네번째라인셋팅
        self.comboBox_4.setCurrentIndex(int(data_json["4"]["action"]))
        self.checkBox_4.setChecked(bool(data_json["4"]["bool"]))
        self.comboBox_4.setStyleSheet("border-width: 3px;")
    def showModal(self):
        return super().exec_()
    def onOKButtonClicked(self):
        self.jsonSave()
        self.accept()
    def onCancelButtonClicked(self):
        self.reject()
    def jsonSave(self):
        option_data = {
            "1":{"action":self.comboBox.currentIndex(),"bool":self.checkBox.isChecked()},
            "2":{"action":self.comboBox_2.currentIndex(),"bool":self.checkBox_2.isChecked()},
            "3":{"action":self.comboBox_3.currentIndex(),"bool":self.checkBox_3.isChecked()},
            "4":{"action":self.comboBox_4.currentIndex(),"bool":self.checkBox_4.isChecked()}
        }
        with open("data.json", "w") as json_file:
            json.dump(option_data, json_file)
            


    def jsonRead(self):
        with open("data.json", "r") as data_json:
            resultset = json.load(data_json)
            return resultset
